<?php

use App\Services\Cms\Fixtures\Stock as S;

/** Shape = GET /public/cms/pages/{slug}. `bodyHtml` is derived from `bodyMarkdown` by the fixture client. */
$page = fn (string $slug, string $title, ?string $subtitle, ?string $hero, string $md, ?string $desc = null, bool $footer = false) => [
    'id' => "page-$slug", 'slug' => $slug, 'title' => $title, 'subtitle' => $subtitle, 'hero' => $hero ? S::media($hero) : null,
    'bodyMarkdown' => $md, 'seo' => ['title' => null, 'description' => $desc ?? $subtitle, 'ogImage' => $hero ? S::media($hero) : null],
    'showInFooter' => $footer, 'publishedAt' => '2026-08-01T09:00:00.000Z', 'updatedAt' => '2026-09-01T09:00:00.000Z',
];

return [
    'home' => $page('home', 'Everything you came for, *in one place.*', 'Run around, cool off, get pampered, eat well. 007 is built for the kind of day that runs from morning to midnight, without a queue at any door.', null, ''),
    'sports' => $page('sports', 'Game on, *any hour.*', 'Two tennis courts, a five-a-side pitch and a basketball court, floodlit until close. Pick your hour and we hold it while you pay.', 'hero-03',
        "Pick a court, see live availability, and hold your slot for ten minutes while you pay. Night slots cost the same as day slots, and the front desk sees exactly what you see, so nobody can sell your hour twice.\n\n## Kit on site\n\nRackets, balls and bibs are available from the Sports Store next door; show your QR code and they are yours for the session.\n\n## Members play first\n\nMembers book before everyone else and pay less. See the [membership plans](/membership).",
        'Live availability for lawn tennis, five-a-side football and basketball at 007 Resort & Spa, Otueke. Hold a slot, pay online, walk in with a QR.'),
    'pool' => $page('pool', 'Cool off, *properly.*', 'Loungers under the palms, a shallow end for the kids and a bar that comes to you. Buy passes for the whole group and everyone gets a QR.', 'hero-02',
        "A big open pool, a shallow end for the children, a lifeguard at every opening hour and loungers along the palms. The poolside bar brings drinks and light bites to you.\n\n- Children under 12 pay the child rate\n- Loungers are included, first come first served\n- Poolside DJ on Saturday nights\n\n![Loungers by the palms](/stock/pool-04-loungers-by-palms-960.webp)",
        'Buy swimming pool day passes for adults and children. One QR ticket per person. 007 Resort & Spa, Otueke.'),
    'spa' => $page('spa', 'Slow down, *on purpose.*', 'Hot stone and deep tissue massage, facials and scrubs in quiet, candle-lit rooms.', 'spa-04',
        "Every treatment starts with tea and a robe and ends with a few quiet minutes before you go. Choose your therapist when you book, and arrive ten minutes early.\n\n## Treatment menu\n\n| Treatment | Time | From |\n| --- | --- | --- |\n| Hot stone massage | 90 min | ₦35,000 |\n| Deep tissue massage | 60 min | ₦25,000 |\n| Express back massage | 30 min | ₦15,000 |\n| Clay facial | 45 min | ₦18,000 |\n| Body scrub | 45 min | ₦22,000 |\n\nIndicative prices; live prices are shown when you book. Steam and sauna are included with treatments over 60 minutes.",
        'Hot stone massage, facials and body treatments at 007 Resort & Spa, Otueke. Book your slot online.'),
    'dining' => $page('dining', 'Fire, pepper *and patience.*', 'A kitchen that cooks to order, a charcoal grill deck and a bar under string lights.', 'dining-06',
        "Suya spiced in-house every morning and turned by hand over real charcoal. The grill deck opens at five because the fire needs an hour to come to temperature.\n\n## From the grill\n\n| Dish | Price |\n| --- | --- |\n| Chicken suya skewers | ₦5,500 |\n| Beef suya, extra pepper | ₦4,500 |\n| Grilled fish and jollof | ₦8,500 |\n\n## Brunch and bar\n\n| Dish | Price |\n| --- | --- |\n| Weekend brunch board | ₦9,000 |\n| Ruby cocktail | ₦4,500 |\n\nMenu highlights; the full menu is at the restaurant. The kitchen is open from 11am, and brunch runs on weekends.",
        'Jollof and grilled fish, charcoal suya, brunch and cocktails at 007 Resort & Spa, Otueke.'),
    'membership' => $page('membership', 'Come every week. *Pay less every time.*', 'Priority court times, free pool days and a private booking line. Pick a plan and pay securely online.', 'membership-02',
        "## What members get\n\n- **Priority court times.** Book before everyone else, every time.\n- **Free pool days.** Included every month, depending on plan.\n- **Member rates.** Lower prices on sport, spa and dining.\n- **A private booking line.** WhatsApp the desk and jump the queue.",
        'Priority court times, free pool days and member rates across 007 Resort & Spa.'),
    'events' => $page('events', "What's on", 'Round robins, match nights, DJs on the pool deck and Sunday yoga. Filter by month or type and add anything to your calendar.', 'events-07', '', 'Match nights, DJs, yoga, cups and celebrations at 007 Resort & Spa, Otueke.'),
    'blog' => $page('blog', 'Stories from *the courts and the deck.*', 'How-tos, guides and news from the resort.', 'hero-05', '', 'Guides, stories and news from 007 Resort & Spa, Otueke.'),
    'gallery' => $page('gallery', 'See it *for yourself.*', 'Courts, pool, spa, food and everything in between.', 'gallery-01', '', 'Photos of the courts, pool, spa, food and events at 007 Resort & Spa.'),
    'about' => $page('about', 'Built for the kind of day that *runs to midnight.*', 'A sports, pool and spa resort in Otueke, Bayelsa.', 'hero-04',
        "007 Resort & Spa brings sport, water, wellness and food together in Otueke. It started with a simple idea: that a good weekend should not need three separate plans and a queue at every door.\n\n![The resort at dusk](/stock/hero-06-pool-party-energy-960.webp)\n\n## One booking system, everywhere\n\nThe court you see online is the court the front desk sees. Tickets, memberships and payments run through the same system, so what you book is what is waiting for you.\n\n- Live availability, no double-booking\n- A QR ticket for every person\n- Staff who can see your booking\n\n## What we care about\n\n**Nobody waits.** Book ahead, walk in, get on with your day.\n\n**Local first.** Hired and supplied from Bayelsa wherever we can.\n\n**Open all day.** From early swims to late suya.",
        'The story of 007 Resort & Spa in Otueke, Bayelsa: sport, pool, spa and hospitality under one roof.'),
    'contact' => $page('contact', 'Say *hello.*', 'Questions, group bookings, events or feedback. We reply fast, especially on WhatsApp.', 'hero-05', '', 'Address, phone, WhatsApp, opening hours and a contact form for 007 Resort & Spa, Otueke, Bayelsa.'),
    'faq' => $page('faq', 'Good *to know.*', 'Booking, tickets, payments, membership and visiting.', 'hero-04', '', 'Answers about booking, tickets, payments, membership and visiting 007 Resort & Spa.'),
    'terms' => $page('terms', 'Terms of use', 'How bookings, tickets and payments work.', null, "## Using this website\n\nBy booking through this website you agree to these terms. Bookings, tickets and memberships are subject to availability and to the cancellation rules shown at the time of booking.\n\n## Payments\n\nPayments are processed by Paystack. We do not store card details.\n\n## Tickets\n\nA QR ticket admits the named person for the date and time shown, once.", null, true),
    'privacy' => $page('privacy', 'Privacy policy', 'What we collect and why.', null, "## What we collect\n\nYour name, email and phone number when you register or book, and your email if you subscribe to updates.\n\n## How we use it\n\nTo confirm bookings, issue tickets, send receipts and, only if you subscribe, our weekly email. Unsubscribe with one click.\n\n## Your choices\n\nContact us to see, correct or delete your data.", null, true),
    'cookies' => $page('cookies', 'Cookie notice', 'What is stored in your browser.', null, "## Cookies we use\n\nA session cookie keeps you signed in and protects forms. We store a small note in your browser if you dismiss the announcement bar or the subscribe prompt. We do not use advertising cookies.", null, true),
];
